### ISSUE TITLE
Provide a /health or alike endpoint for live/readiness probes

### ISSUE THREAD

**Issue by jjo** [wavefrontHQ/prometheus-storage-adapter#12]
Although not completely sure, I've observed that connection pooling can become stale,
it would be very helpful to have a /health or alike endpoint allowing us to implement
proper readiness / liveness Kubernetes probes

**Comment by jjo** [comment]
FYI using below container stanza to workaround this:
```
        livenessProbe:
          exec:
            # Ok if grepped 404 from http://localhost:PORT/
            command:
            - sh
            - -c
            - |
              wget -qO- http://127.0.0.1:1234/ 2>&1 | grep -q 404
          periodSeconds: 30
          initialDelaySeconds: 30

```
